---
title: "Power Architecture"
---
%% v1.0.3

graph LR

subgraph Energy-Storage
Primary-Battery
Secondary-Battery
end

Primary-Battery & Secondary-Battery --> ES
subgraph Emergency-Stop
ES[Kill-Switch \n & Main Relay]
end

ES --> Primary-Distribution & Secondary-Distribution
subgraph Power-Distribution
Primary-Distribution
Secondary-Distribution
end

Primary-Distribution & Secondary-Distribution --> Downstream-Devices
subgraph Downstream-Devices
direction LR
DC/DC-Converters
Raspberry-Pi
Motors
Sensors
...
end
