---
title: "Power Architecture"
---
%% v1.0.2

graph LR

subgraph Energy-Storage
Primary-Battery
Secondary-Battery
end

Primary-Battery & Secondary-Battery --> Kill-Switch
subgraph Emergency-Stop
Kill-Switch
end

Kill-Switch --> Primary-Distribution & Secondary-Distribution
subgraph Power-Distribution
Primary-Distribution
Secondary-Distribution
end

Primary-Distribution & Secondary-Distribution --> Downstream-Devices
subgraph Downstream-Devices
direction LR
DC/DC-Converters
Raspberry-Pi
Motors
Sensors
...
end
