---
title: "Wiring Diagram: Power"
---
 graph LR

Primary-Battery --> |10mm<sup>2| Primary-Fuse
Secondary-Battery --> |1,5mm<sup>2| Secondary-Fuse
subgraph Circuit-Braker
    direction LR
    Primary-Fuse --> |10mm<sup>2| Primary-Relais
    Primary-Fuse --> |1,5mm<sup>2| Kill-Switch --> |1,5mm<sup>2| Primary-Relais & Secondary-Relais  
    Secondary-Fuse --> |1,5mm<sup>2| Secondary-Relais
end

Primary-Relais --> |10mm<sup>2| PD
Secondary-Relais --> |1,5mm<sup>2| SD
subgraph Power-Distribution
    direction LR
    PD[Primary-Distribution \n & Fusing] --> Servo
    SD[Secondary-Distribution \n & Fusing] --> 12V-Rail
    
end

Servo --> |????| Steering
subgraph Steering
    direction LR 
    Bus-Controller --- Servo#1 --- |????| Servo#2 --- |????| Servo#3 --- |????| Servo#4
end


PD --> |4x 4mm<sup>2| Drive-Train
12V-Rail --> |4x 0,5mm<sup>2| Drive-Train
subgraph Drive-Train
    direction TB
    ESC#1 --> |4mm<sup>2| Motor#1
    ESC#2 --> |4mm<sup>2| Motor#2
    ESC#3 --> |4mm<sup>2| Motor#3
    ESC#4 --> |4mm<sup>2| Motor#4
end

SD --> |????| Control
subgraph Control
    test
end

linkStyle 0,2,3,4,5,7 stroke:red
linkStyle 1,6,8 stroke:yellow
