---
titel: Wiring Diagram
---

graph LR

subgraph Circuit-Breaker
    direction TB
    Kill-Switch <--> Relais
end


subgraph Drive-Train
    direction TB
    ESC#1 --> Motor#1
    ESC#2 --> Motor#2
    ESC#3 --> Motor#3
    ESC#4 --> Motor#4
end

subgraph Steering
    direction LR
    Bus-Controller ---
    Servo#1 ---
    Servo#2 ---
    Servo#3 ---
    Servo#4
end

subgraph Computing
    direction LR
    Backup-Battery
    Logic-Rail
    Raspberry-PI
    Backup-Battery --> Logic-Rail --> Raspberry-PI & Computer
end

Battery --> Fuse --> Circuit-Breaker --> 
Power-Distribution --> Computing & Steering & Drive-Train